# Generated by Django 2.1.7 on 2019-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='facebook',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
