# Generated by Django 2.1.7 on 2019-03-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='cardinal_point',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='close_time',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact1',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact2',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='-', max_length=2083),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='facebook',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_map',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.CharField(default='-', max_length=2083),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_time',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone1',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone2',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
