# Generated by Django 2.1.7 on 2019-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190307_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_map',
            field=models.CharField(default='-', max_length=2083),
        ),
    ]
