# Generated by Django 2.1.7 on 2019-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20190312_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='close_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
