# Generated by Django 2.1.7 on 2019-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20190312_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='close_time',
            field=models.TimeField(blank=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact #1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact #2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_time',
            field=models.TimeField(blank=True, verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=12, verbose_name='Phone #1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=12, verbose_name='Phone #2'),
        ),
    ]
