# Generated by Django 2.1.7 on 2019-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20190312_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='close_time',
            field=models.TimeField(null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_time',
            field=models.TimeField(null=True, verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone1',
            field=models.IntegerField(null=True, verbose_name='Phone #1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone2',
            field=models.IntegerField(null=True, verbose_name='Phone #2'),
        ),
    ]
