# Generated by Django 2.1.7 on 2019-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_auto_20190312_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cardinal_point',
            field=models.CharField(choices=[('None', 'None'), ('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West'), ('Central', 'Central')], default='None', max_length=7),
        ),
    ]
