# Generated by Django 2.1.7 on 2019-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20190313_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Name 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Name 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone1',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number 2'),
        ),
    ]
